name: Github Actions Project Awesome Inc
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    jobs:
      Explore-GitHub-Actions:
        name: ${{ github.actor }} is testing out Github Actions
        runs-on: ubuntu-latest
        steps:
          - name: Clone repository
            uses: actions/checkout@v3
          - name: Change Working directory
            run: cd module3_task0
          - name: Validate makefile
            run: make help
